spring:
  application:
    name: redis-demo

  ## Database Config ##
  datasource:
    url: jdbc:postgresql://localhost:5432/countries
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  ## Redis & Cache Config ##
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

## Redis Cache Entry TTL Values ##
redis:
  cache:
    ttl: 120
    countryNames:
      ttl: 60
    countryISO:
      ttl: 60

## Context Path ##
server:
  servlet:
    context-path: /api
